// Generated by https://quicktype.io

export interface Coffee {
    id:        string;
    name:      string;
    image:     string;
    price:     string;
    rating:    number | null | string;
    votes:     number;
    popular:   boolean;
    available: boolean;
}
